name: Create GitHub release

on:
 push:
  tags:
   - 'v*.*.*'

jobs:
 release:
  name: Create new github release using version tag
  runs-on: ubuntu-latest
  steps:
   - name: Checkout
     uses: actions/checkout@v2
   - name: Create release
     uses: softprops/action-gh-release@v1
